---
  extends: airbnb
  env:
    node: true
    mocha: true
    es6: true
  parserOptions:
    sourceType: module
  rules:
    no-console: 0
    generator-star-spacing:
      - 2
      - before: true
        after: true
    no-shadow: 0
    require-yield: 0
    no-param-reassign: 0
    comma-dangle:
      - error
      - never
    no-underscore-dangle: 0
    import/no-extraneous-dependencies:
      - 2
      - devDependencies: true
    import/order:
      - error
    func-names: 0
    no-unused-expressions: 0
    prefer-arrow-callback: 1
    no-use-before-define:
      - 2
      - functions: false
    space-before-function-paren:
      - 2
      - always
    max-len:
      - 2
      - 120
      - 2
    semi:
      - 2
      - never
    strict: 0
    arrow-parens:
      - 2
      - always
    jsx-a11y/href-no-hash: 0
    react/jsx-filename-extension: 0
