apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: JAEGER_HOST
            value: jaeger-agent.{{ .Release.Namespace }}
        ports:
        - containerPort: 3000
          name: server
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        livenessProbe:
          httpGet:
            path: /healthz
            port: server
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: server
            scheme: HTTP
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 5
