apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        env:
          - name: JAEGER_HOST
            value: jaeger-agent.{{ .Release.Namespace }}
        ports:
        - containerPort: 3000
          name: server
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
