swagger: "2.0"
info:
  version: "0.0.1"
  title: User API
  description: API Gateway
basePath: /
tags:
  - name: user
    description: User API
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    x-swagger-router-controller: userController
    get:
      operationId: get
      tags:
        - user
      description: Return with users
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /healthz:
    x-swagger-router-controller: healthzController
    get:
      description: Returns application health
      responses:
        "200":
          description: Success
          schema:
            type: object
            properties:
              status:
                type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  User:
    properties:
      id:
        type: string
      name:
        type: string
    required:
      - id
  ErrorResponse:
    properties:
      message:
        type: string
    required:
      - message
