apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: server
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
  type: {{ if .Values.public }}LoadBalancer{{ else }}NodePort{{ end }}
