apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    app: {{ .Chart.Name }}
    jaeger-infra: {{ .Chart.Name }}-deployment
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        jaeger-infra: {{ .Chart.Name }}-pod
    spec:
        containers:
        -   env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
            image: "{{ .Values.image.repository }}"
            name: {{ .Chart.Name }}
            ports:
              - containerPort: 5775
                protocol: UDP
              - containerPort: 6831
                protocol: UDP
              - containerPort: 6832
                protocol: UDP
              - containerPort: 16686
                protocol: TCP
              - containerPort: 9411
                protocol: TCP
            readinessProbe:
              httpGet:
                path: "/"
                port: 16686
              initialDelaySeconds: 5
