apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: {{ .Chart.Name }}
    jaeger-infra: zipkin-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  clusterIP: None
  selector:
    jaeger-infra: {{ .Chart.Name }}-pod
