apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-collector
  labels:
    app: {{ .Chart.Name }}
    jaeger-infra: collector-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: {{ .Chart.Name }}-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: {{ .Chart.Name }}-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    jaeger-infra: {{ .Chart.Name }}-pod
  type: ClusterIP
