apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-query
  labels:
    app: {{ .Chart.Name }}
    jaeger-infra: {{ .Chart.Name }}-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    jaeger-infra: {{ .Chart.Name }}-pod
  type: NodePort
